### ISSUE TITLE
Error in UseMethod("select_") : no applicable method for 'select_' applied to an object of class "c('TxDb', 'AnnotationDb', 'envRefClass', '.environment', 'refClass', 'environment', 'refObject', 'AssayData')"

### ISSUE THREAD

**Issue by 674040463** [NWPU-903PR/DMDeepm6A1.0#1] opened 2019-10-23 19:25 UTC
Hi, Thank you for making your software available.
When I try to run, I get this error 
`Error in UseMethod("select_") : no applicable method for 'select_' applied to an object of class "c('TxDb', 'AnnotationDb', 'envRefClass', '.environment', 'refClass', 'environment', 'refObject', 'AssayData')"`
Although, after Google and other user meet the same error because of "AnnotationDbi::select()" so as not to clash with dplyr "select".
But  I can not unload the dplyr package because of this package depend on Guitar package which need dplyr
What could I do for this error?  :)

Best wishes

**Comment by jjovelc** [comment] 2019-10-24 16:44
I have the same problem in an installation I did as super user, with R 3.6. 

Then I tried a different installation in R 3.5 (which is in my conda environment) and it runs without problems with the toy data provided. However, when I try to run it with my own data, I get the following problem:

caught segfault - 'memory not mapped'

Any help will be highly appreciated.

**Comment by jjovelc** [comment] 2019-10-25 15:45
It is me again, I did a third installation in my local linux computer (Ubuntu) and here FunDMDeep-m6
A runs further, but eventually collapses with the following error message. Any help will be highly appreciated.

[1] "Peak calling result: "
[1] "6319 peaks detected on merged data."
[1] "Please check 'peak.bed/xls' under /home/juan/juan/UofA/projects_analysis/brunoSaleme/2019/IP_190711s1/FunDMDeep-m6A/DMDeepm6A_out/exomepeak_untreated"
[1] "1358 consistent peaks detected on every replicates. (Recommended list)"
[1] "Please check 'con_peak.bed/xls' under /home/juan/juan/UofA/projects_analysis/brunoSaleme/2019/IP_190711s1/FunDMDeep-m6A/DMDeepm6A_out/exomepeak_untreated"
[1] "Detecting sites for IP/Input paire 1 ----------------------------"
[1] "Converting BED12 to GRangesList"
[1] "It may take a few minutes"
[1] "Cutting peak to Single Base..."
Time difference of 1.053377 mins
[1] "Searching peak for motifs..."
Time difference of 1.378228 mins
[1] "Making input from peak region..."
[1] "Counting reads for single base..."
Error in ba$pos[ID_negative] <- ba$pos[ID_negative] + ba$qwidth[ID_negative] -  : 
  NAs are not allowed in subscripted assignments

**Comment by NWPU-903PR** [comment] 2019-10-27 02:52
> It is me again, I did a third installation in my local linux computer (Ubuntu) and here FunDMDeep-m6
> A runs further, but eventually collapses with the following error message. Any help will be highly appreciated.
> 
> [1] "Peak calling result: "
> [1] "6319 peaks detected on merged data."
> [1] "Please check 'peak.bed/xls' under /home/juan/juan/UofA/projects_analysis/brunoSaleme/2019/IP_190711s1/FunDMDeep-m6A/DMDeepm6A_out/exomepeak_untreated"
> [1] "1358 consistent peaks detected on every replicates. (Recommended list)"
> [1] "Please check 'con_peak.bed/xls' under /home/juan/juan/UofA/projects_analysis/brunoSaleme/2019/IP_190711s1/FunDMDeep-m6A/DMDeepm6A_out/exomepeak_untreated"
> [1] "Detecting sites for IP/Input paire 1 ----------------------------"
> [1] "Converting BED12 to GRangesList"
> [1] "It may take a few minutes"
> [1] "Cutting peak to Single Base..."
> Time difference of 1.053377 mins
> [1] "Searching peak for motifs..."
> Time difference of 1.378228 mins
> [1] "Making input from peak region..."
> [1] "Counting reads for single base..."
> Error in ba$pos[ID_negative] <- ba$pos[ID_negative] + ba$qwidth[ID_negative] - :
> NAs are not allowed in subscripted assignments

The error looks like there is something wrong when reading the stand of your input bam files while this may be caused by a small bug in the code. I have fixed this and upload to github please try to install the new version from github and try again.

**Comment by NWPU-903PR** [comment] 2019-10-27 03:05
> Hi, Thank you for making your software available.
> When I try to run, I get this error
> `Error in UseMethod("select_") : no applicable method for 'select_' applied to an object of class "c('TxDb', 'AnnotationDb', 'envRefClass', '.environment', 'refClass', 'environment', 'refObject', 'AssayData')"`
> Although, after Google and other user meet the same error because of "AnnotationDbi::select()" so as not to clash with dplyr "select".
> But I can not unload the dplyr package because of this package depend on Guitar package which need dplyr
> What could I do for this error? :)
> 
> Best wishes

Hi thank you for interested in our package. As jjovelc said, you may try R 3.5. Because there is a big change in the depending Guitar package from R 3.5 to R 3.6. I'll try to update our package to make it work in R 3.6 soon.

Best regards

**Comment by jjovelc** [comment] 2019-10-28 12:53
Dear Author, thank you very much for trying to fix the possible bug. I tried the corrected version of your software, but my run still die at the same point. Here the error message:

[1] "Peak calling result: "
[1] "6319 peaks detected on merged data."
[1] "Please check 'peak.bed/xls' under /home/juan/juan/UofA/projects_analysis/brunoSaleme/2019/IP_190711s1/FunDMDeep-m6A/DMDeepm6A_out/exomepeak_untreated"
[1] "1358 consistent peaks detected on every replicates. (Recommended list)"
[1] "Please check 'con_peak.bed/xls' under /home/juan/juan/UofA/projects_analysis/brunoSaleme/2019/IP_190711s1/FunDMDeep-m6A/DMDeepm6A_out/exomepeak_untreated"
[1] "Detecting sites for IP/Input paire 1 ----------------------------"
[1] "Converting BED12 to GRangesList"
[1] "It may take a few minutes"
[1] "Cutting peak to Single Base..."
Time difference of 1.065789 mins
[1] "Searching peak for motifs..."
Time difference of 1.284774 mins
[1] "Making input from peak region..."
[1] "Counting reads for single base..."
Error in ba$pos[ID_negative] <- ba$pos[ID_negative] + ba$qwidth[ID_negative] -  : 
  NAs are not allowed in subscripted assignments

**Closed as completed** 2021-12-09 09:53 UTC

**Comment by NWPU-903PR** [comment] 2021-12-09 09:54
Hi, I have updated the package and the installation instruction.
